name: Execute functional tests

on: [push, workflow_dispatch]

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npx cypress run
